(function(i,e){'use strict';var r=(/chrom(e|ium)/.test(window.navigator.userAgent.toLowerCase()));if(r){var a=!1;if(window.performance){var n=window.performance.getEntriesByType('navigation');if(n.length>0&&n[0].type==='back_forward'){a=!0}
else if(window.performance.navigation&&window.performance.navigation.type===window.performance.navigation.TYPE_BACK_FORWARD){a=!0}};if(a){var o=e.attachBehaviors;e.attachBehaviors=function(e,a){setTimeout(function(e,a){o(e,a)},300)}}}})(jQuery,Drupal);;
(function(e,i){var t={postponed:[]};i.states=t;function a(e,t){return t&&typeof e!=='undefined'?!e:e};function r(e,t){if(e===t){return typeof e==='undefined'?e:!0};return typeof e==='undefined'||typeof t==='undefined'};function s(e,t){if(typeof e==='undefined'){return t};if(typeof t==='undefined'){return e};return e&&t};i.behaviors.states={attach:function(i,n){var a=e(i).find('[data-drupal-states]'),s=a.length,o=function(i){var n=JSON.parse(a[i].getAttribute('data-drupal-states'));Object.keys(n||{}).forEach(function(r){new t.Dependent({element:e(a[i]),state:t.State.sanitize(r),constraints:n[r]})})};for(var r=0;r<s;r++){o(r)}
while(t.postponed.length){t.postponed.shift()()}}};t.Dependent=function(t){var i=this;e.extend(this,{values:{},oldValue:null},t);this.dependees=this.getDependees();Object.keys(this.dependees||{}).forEach(function(e){i.initializeDependee(e,i.dependees[e])})};t.Dependent.comparisons={RegExp:function(e,t){return e.test(t)},Function:function(e,t){return e(t)},Number:function(e,t){return typeof t==='string'?r(e.toString(),t):r(e,t)}};t.Dependent.prototype={initializeDependee:function(i,n){var r=this;this.values[i]={};Object.keys(n).forEach(function(a){var s=n[a];if(e.inArray(s,n)===-1){return};s=t.State.sanitize(s);r.values[i][s.name]=null;e(i).on('state:'.concat(s),{selector:i,state:s},function(e){r.update(e.data.selector,e.data.state,e.value)});new t.Trigger({selector:i,state:s})})},compare:function(e,i,n){var a=this.values[i][n.name];if(e.constructor.name in t.Dependent.comparisons){return t.Dependent.comparisons[e.constructor.name](e,a)};return r(e,a)},update:function(e,t,i){if(i!==this.values[e][t.name]){this.values[e][t.name]=i;this.reevaluate()}},reevaluate:function(){var e=this.verifyConstraints(this.constraints);if(e!==this.oldValue){this.oldValue=e;e=a(e,this.state.invert);this.element.trigger({type:'state:'.concat(this.state),value:e,trigger:!0})}},verifyConstraints:function(t,i){var n;if(e.isArray(t)){var u=e.inArray('xor',t)===-1,l=t.length;for(var r=0;r<l;r++){if(t[r]!=='xor'){var o=this.checkConstraints(t[r],i,r);if(o&&(u||n)){return u};n=n||o}}}
else if(e.isPlainObject(t)){for(var a in t){if(t.hasOwnProperty(a)){n=s(n,this.checkConstraints(t[a],i,a));if(n===!1){return!1}}}};return n},checkConstraints:function(e,i,n){if(typeof n!=='string'||/[0-9]/.test(n[0])){n=null}
else if(typeof i==='undefined'){i=n;n=null};if(n!==null){n=t.State.sanitize(n);return a(this.compare(e,i,n),n.invert)};return this.verifyConstraints(e,i)},getDependees:function(){var e={};var t=this.compare;this.compare=function(t,i,n){(e[i]||(e[i]=[])).push(n.name)};this.verifyConstraints(this.constraints);this.compare=t;return e}};t.Trigger=function(i){e.extend(this,i);if(this.state in t.Trigger.states){this.element=e(this.selector);if(!this.element.data('trigger:'.concat(this.state))){this.initialize()}}};t.Trigger.prototype={initialize:function(){var i=this,e=t.Trigger.states[this.state];if(typeof e==='function'){e.call(window,this.element)}
else{Object.keys(e||{}).forEach(function(t){i.defaultTrigger(t,e[t])})};this.element.data('trigger:'.concat(this.state),!0)},defaultTrigger:function(i,n){var r=n.call(this.element);this.element.on(i,e.proxy(function(e){var t=n.call(this.element,e);if(r!==t){this.element.trigger({type:'state:'.concat(this.state),value:t,oldValue:r});r=t}},this));t.postponed.push(e.proxy(function(){this.element.trigger({type:'state:'.concat(this.state),value:r,oldValue:null})},this))}};t.Trigger.states={empty:{keyup:function(){return this.val()===''}},checked:{change:function(){var t=!1;this.each(function(){t=e(this).prop('checked');return!t});return t}},value:{keyup:function(){if(this.length>1){return this.filter(':checked').val()||!1};return this.val()},change:function(){if(this.length>1){return this.filter(':checked').val()||!1};return this.val()}},collapsed:{collapsed:function(e){return typeof e!=='undefined'&&'value' in e?e.value:!this.is('[open]')}}};t.State=function(e){this.pristine=e;this.name=e;var i=!0;do{while(this.name.charAt(0)==='!'){this.name=this.name.substring(1);this.invert=!this.invert};if(this.name in t.State.aliases){this.name=t.State.aliases[this.name]}
else{i=!1}}
while(i);};t.State.sanitize=function(e){if(e instanceof t.State){return e};return new t.State(e)};t.State.aliases={enabled:'!disabled',invisible:'!visible',invalid:'!valid',untouched:'!touched',optional:'!required',filled:'!empty',unchecked:'!checked',irrelevant:'!relevant',expanded:'!collapsed',open:'!collapsed',closed:'collapsed',readwrite:'!readonly'};t.State.prototype={invert:!1,toString:function(){return this.name}};var n=e(document);n.on('state:disabled',function(t){if(t.trigger){e(t.target).prop('disabled',t.value).closest('.js-form-item, .js-form-submit, .js-form-wrapper').toggleClass('form-disabled',t.value).find('select, input, textarea').prop('disabled',t.value)}});n.on('state:required',function(t){if(t.trigger){if(t.value){var n='label'.concat(t.target.id?'[for='.concat(t.target.id,']'):''),i=e(t.target).attr({required:'required','aria-required':'true'}).closest('.js-form-item, .js-form-wrapper').find(n);if(!i.hasClass('js-form-required').length){i.addClass('js-form-required form-required')}}
else{e(t.target).removeAttr('required aria-required').closest('.js-form-item, .js-form-wrapper').find('label.js-form-required').removeClass('js-form-required form-required')}}});n.on('state:visible',function(t){if(t.trigger){e(t.target).closest('.js-form-item, .js-form-submit, .js-form-wrapper').toggle(t.value)}});n.on('state:checked',function(t){if(t.trigger){e(t.target).prop('checked',t.value)}});n.on('state:collapsed',function(t){if(t.trigger){if(e(t.target).is('[open]')===t.value){e(t.target).find('> summary').trigger('click')}}})})(jQuery,Drupal);;
(function(t){t(document).unbind('state:disabled');t(document).bind('state:disabled',function(e){if(e.trigger){t(e.target).attr('disabled',e.value).closest('.form-item, .form-submit, .form-wrapper').toggleClass('form-disabled',e.value).find(':input').attr('disabled',e.value)}})})(jQuery);;
(function(e,t){'use strict';t.webform=t.webform||{};t.webform.states=t.webform.states||{};t.webform.states.slideDown=t.webform.states.slideDown||{};t.webform.states.slideDown.duration='slow';t.webform.states.slideUp=t.webform.states.slideUp||{};t.webform.states.slideUp.duration='fast';e.fn.hasData=function(e){return(typeof this.data(e)!=='undefined')};e.fn.isWebform=function(){return e(this).closest('form.webform-submission-form, form[id^="webform"], form[data-is-webform]').length?!0:!1};e.fn.isWebformElement=function(){return(e(this).isWebform()||e(this).closest('[data-is-webform-element]').length)?!0:!1};t.states.Trigger.states.empty.change=function(){return this.val()===''};var n=t.states;t.states.Dependent.prototype.compare=function(t,r,a){var o=this.values[r][a.name],i=t.constructor.name;if(!i){i=e.type(t);i=i.charAt(0).toUpperCase()+i.slice(1)};if(i in n.Dependent.comparisons){return n.Dependent.comparisons[i](t,o)};if(t.constructor.name in n.Dependent.comparisons){return n.Dependent.comparisons[t.constructor.name](t,o)};return u(t,o)};function u(e,t){if(e===t){return typeof e==='undefined'?e:!0};return typeof e==='undefined'||typeof t==='undefined'};t.states.Dependent.comparisons.Object=function(e,t){if('pattern' in e){return(new RegExp(e['pattern'])).test(t)}
else if('!pattern' in e){return!((new RegExp(e['!pattern'])).test(t))}
else if('less' in e){return(t!==''&&parseFloat(e['less'])>parseFloat(t))}
else if('less_equal' in e){return(t!==''&&parseFloat(e['less_equal'])>=parseFloat(t))}
else if('greater' in e){return(t!==''&&parseFloat(e['greater'])<parseFloat(t))}
else if('greater_equal' in e){return(t!==''&&parseFloat(e['greater_equal'])<=parseFloat(t))}
else if('between' in e||'!between' in e){if(t===''){return!1};var s=e['between']||e['!between'],r=s.split(':'),i=r[0],o=(typeof r[1]!=='undefined')?r[1]:null,n=(i===null||i===''||parseFloat(t)>=parseFloat(i)),f=(o===null||o===''||parseFloat(t)<=parseFloat(o)),a=(n&&f);return(e['!between'])?!a:a}
else{return e.indexOf(t)!==!1}};var i=e(document);i.on('state:required',function(t){if(t.trigger&&e(t.target).isWebformElement()){var i=e(t.target);r(i.find('input[type="file"]'),t.value);if(i.is('.js-form-type-radios, .js-form-type-webform-radios-other, .js-webform-type-radios, .js-webform-type-webform-radios-other, .js-webform-type-webform-entity-radios, .webform-likert-table')){i.toggleClass('required',t.value);r(i.find('input[type="radio"]'),t.value)};if(i.is('.js-form-type-checkboxes, .js-form-type-webform-checkboxes-other, .js-webform-type-checkboxes, .js-webform-type-webform-checkboxes-other')){i.toggleClass('required',t.value);var n=i.find('input[type="checkbox"]');if(t.value){n.on('click',a);o(i)}
else{n.off('click',a);r(n,!1)}};if(i.is('.js-webform-tableselect')){i.toggleClass('required',t.value);var d=i.is('[multiple]');if(d){var f=i.find('tbody'),n=f.find('input[type="checkbox"]');s(i,n);if(t.value){n.on('click change',a);o(f)}
else{n.off('click change ',a);r(f,!1)}}
else{var u=i.find('input[type="radio"]');s(i,u);r(u,t.value)}};if(i.is('.js-form-type-webform-select-other, .js-webform-type-webform-select-other')){var l=i.find('select');r(l,t.value);s(i,l)};if(i.find('> label:not([for])').length){i.find('> label').toggleClass('js-form-required form-required',t.value)};if(i.is('.js-webform-type-radios, .js-webform-type-checkboxes, fieldset')){i.find('legend span.fieldset-legend:not(.visually-hidden)').toggleClass('js-form-required form-required',t.value)};if(i.is('fieldset')){i.removeAttr('required aria-required')}}});i.on('state:checked',function(t){if(t.trigger){e(t.target).trigger('change')}});i.on('state:readonly',function(t){if(t.trigger&&e(t.target).isWebformElement()){e(t.target).prop('readonly',t.value).closest('.js-form-item, .js-form-wrapper').toggleClass('webform-readonly',t.value).find('input, textarea').prop('readonly',t.value);e(t.target).trigger('webform:readonly').find('select, input, textarea, button').trigger('webform:readonly')}});i.on('state:visible state:visible-slide',function(t){if(t.trigger&&e(t.target).isWebformElement()){if(t.value){e(':input',t.target).addBack().each(function(){c(this);l(this)})}
else{e(':input',t.target).addBack().each(function(){d(this);m(this);l(this)})}}});i.on('state:visible-slide',function(r){if(r.trigger&&e(r.target).isWebformElement()){var i=r.value?'slideDown':'slideUp',o=t.webform.states[i].duration;e(r.target).closest('.js-form-item, .js-form-submit, .js-form-wrapper')[i](o)}});t.states.State.aliases['invisible-slide']='!visible-slide';i.on('state:disabled',function(t){if(t.trigger&&e(t.target).isWebformElement()){e(t.target).prop('disabled',t.value).closest('.js-form-item, .js-form-submit, .js-form-wrapper').toggleClass('form-disabled',t.value).find('select, input, textarea, button').prop('disabled',t.value);var r=e(t.target).find(':input[type="hidden"][name$="[fids]"]');if(r.length){if(e(t.target).is('fieldset')){e(t.target).prop('disabled',!1)};r.removeAttr('disabled')};e(t.target).trigger('webform:disabled').find('select, input, textarea, button').trigger('webform:disabled')}});t.behaviors.webformCheckboxesRequired={attach:function(t){e('.js-form-type-checkboxes.required, .js-form-type-webform-checkboxes-other.required, .js-webform-type-checkboxes.required, .js-webform-type-webform-checkboxes-other.required, .js-webform-type-webform-radios-other.checkboxes',t).once('webform-checkboxes-required').each(function(){var t=e(this);t.find('input[type="checkbox"]').on('click',a);setTimeout(function(){o(t)})})}};t.behaviors.webformRadiosRequired={attach:function(t){e('.js-form-type-radios, .js-form-type-webform-radios-other, .js-webform-type-radios, .js-webform-type-webform-radios-other, .js-webform-type-webform-entity-radios, .js-webform-type-webform-scale',t).once('webform-radios-required').each(function(){var t=e(this);setTimeout(function(){f(t)})})}};t.behaviors.webformTableSelectRequired={attach:function(t){e('.js-webform-tableselect.required',t).once('webform-tableselect-required').each(function(){var t=e(this),r=t.find('tbody'),i=t.is('[multiple]');if(i){r.find('input[type="checkbox"]').on('click change',function(){o(r)})};setTimeout(function(){i?o(r):f(t)})})}};function o(e){var t=e.find('input[type="checkbox"]').first(),i=e.find('input[type="checkbox"]').is(':checked');r(t,!i);s(e,t)};function f(e){var t=e.find('input[type="radio"]'),i=e.hasClass('required');r(t,i);s(e,t)};function a(){var t=e(this).closest('.js-webform-type-checkboxes, .js-webform-type-webform-checkboxes-other');o(t)};function l(t){var r=e(t),o=t.type,s=t.tagName.toLowerCase(),i=['webform.states'];if(o==='checkbox'||o==='radio'){r.trigger('change',i).trigger('blur',i)}
else if(s==='select'){if(r.closest('.webform-type-address').length){if(!r.data('webform-states-address-initialized')&&r.attr('autocomplete')==='country'&&r.val()===r.find('option[selected]').attr('value')){return};r.data('webform-states-address-initialized',!0)};r.trigger('change',i).trigger('blur',i)}
else if(o!=='submit'&&o!=='button'&&o!=='file'){var a=(e.fn.inputmask&&r.hasClass('js-webform-input-mask'));a&&r.inputmask('remove');r.trigger('input',i).trigger('change',i).trigger('keydown',i).trigger('keyup',i).trigger('blur',i);a&&r.inputmask()}};function d(t){var r=e(t),i=t.type,a=t.tagName.toLowerCase();if(r.prop('required')&&!r.hasData('webform-required')){r.data('webform-required',!0)};if(!r.hasData('webform-value')){if(i==='checkbox'||i==='radio'){r.data('webform-value',r.prop('checked'))}
else if(a==='select'){var o=[];r.find('option:selected').each(function(e,t){o[e]=t.value});r.data('webform-value',o)}
else if(i!=='submit'&&i!=='button'){r.data('webform-value',t.value)}}};function c(t){var r=e(t),o=r.data('webform-value');if(typeof o!=='undefined'){var i=t.type,s=t.tagName.toLowerCase();if(i==='checkbox'||i==='radio'){r.prop('checked',o)}
else if(s==='select'){e.each(o,function(e,t){t=t.replace(/'/g,'\\\'');r.find('option[value=\''+t+'\']').prop('selected',!0)})}
else if(i!=='submit'&&i!=='button'){t.value=o};r.removeData('webform-value')};var a=r.data('webform-required');if(typeof a!=='undefined'){if(a){r.prop('required',!0)};r.removeData('webform-required')}};function m(t){var i=e(t);if(i.closest('[data-webform-states-no-clear]').length){return};var r=t.type,o=t.tagName.toLowerCase();if(r==='checkbox'||r==='radio'){i.prop('checked',!1)}
else if(o==='select'){if(i.find('option[value=""]').length){i.val('')}
else{t.selectedIndex=-1}}
else if(r!=='submit'&&r!=='button'){t.value=(r==='color')?'#000000':''};i.prop('required',!1)};function r(e,t){var r=(e.attr('type')==='radio'||e.attr('type')==='checkbox');if(t){if(r){e.attr({'required':'required'})}
else{e.attr({'required':'required','aria-required':'true'})}}
else{if(r){e.removeAttr('required')}
else{e.removeAttr('required aria-required')}}};function s(e,t){if(e.attr('data-msg-required')){t.attr('data-msg-required',e.attr('data-msg-required'))}}})(jQuery,Drupal);;
(function(e,r){'use strict';e(document).on('state:required',function(r){if(r.trigger&&e(r.target).isWebform()){var i=e(r.target);if(i.is('.js-form-wrapper.panel')){if(r.value){i.find('.panel-heading .panel-title').addClass('js-form-required form-required')}
else{i.find('.panel-heading .panel-title').removeClass('js-form-required form-required')}}}})})(jQuery,Drupal);;
(function(e,c,i){'use strict';c.behaviors.ckeditorAccordion={attach:function(c,a){var t=e('.ckeditor-accordion');if(t.length>0){t.each(function(){var c=e(this);if(c.hasClass('styled')){return};if(!i.ckeditorAccordion.accordionStyle.collapseAll){c.children('dt:first').addClass('active');c.children('dd:first').addClass('active');c.children('dd:first').css('display','block')};c.children('dt').each(function(){var c=e(this),i=c.text().trim(),t=c.hasClass('active')?' active':'';c.html('<a class="ckeditor-accordion-toggler" href="#"><span class="ckeditor-accordion-toggle'+t+'"></span>'+i+'</a>')});c.addClass('styled').removeClass('ckeditor-accordion').wrap('<div class="ckeditor-accordion-container"></div>');c.trigger('ckeditorAccordionAttached')});e('body').once('ckeditorAccordionToggleEvent').on('click','.ckeditor-accordion-toggler',function(t){var c=e(this).parent(),a=c.parent();if(c.hasClass('active')){c.removeClass('active');c.next().slideUp()}
else{if(!i.ckeditorAccordion.accordionStyle.keepRowsOpen){a.children('dt.active').removeClass('active').children('a').removeClass('active');a.children('dd.active').slideUp(function(){e(this).removeClass('active')})};c.addClass('active');c.next().slideDown(300).addClass('active')};t.preventDefault()})}}}})(jQuery,Drupal,drupalSettings);;
(function(e){'use strict';var t=Date.now();function o(e,t){var o;return function(){var a=this,i=arguments;clearTimeout(o);o=setTimeout(function(){return e.apply(a,i)},t)}};function a(e){var t=document.createElement('a');t.href=e;return t.hostname===location.hostname?'this embedded media':t.hostname};Drupal.theme.ndpCookiesCoverplate=Drupal.theme.ndpCookiesCoverplate||function(e,t){return'<div class="coverplate"><p>Content from <i>'+e+'</i> is blocked until you accept '+t+' cookies.</p><button href="" class="accept">Accept cookies</button></div>'};Drupal.behaviors.ndpCookies={attach:function(o,i){e('iframe[data-cookiecategory], embed[data-cookiecategory], script[data-cookiecategory]',o).each(function(){var o=e(this),s=a(o.data('src')),c=o.data('cookiecategory'),n=e(Drupal.theme.ndpCookiesCoverplate(s,c));if(s==='platform.twitter.com'){return};var i;if(o.is('script')&&o.prev('div').length>0&&o.prev('div').children().length===0){i=o.prev('div')}
else if(o.is('script')&&o.prev('blockquote.instagram-media').length>0){i=o.prev('blockquote.instagram-media');n.css('position','absolute');i.css('position','relative')};if(!i){i=o};n.css('min-height',i.height()).css('min-width',i.width()).css('z-index',1);n.children('.accept').on('click',null,c,function(e){var i=CookieControl.config(),o=i.optionalCookies,n=o.length;for(var t=0;t<n;t++){var a=o[t].name.toLowerCase();if(a===e.data){CookieControl.changeCategory(t,!0)}}});var r='coverplate-'+(t++);n.attr('id',r);o.attr('aria-describedby',r);if(o.parent('.video-embed-field-responsive-video').length>0){o.before(n.css('position','absolute').css('min-height','').css('min-width','').css('height','100%').css('top',0))}
else if(o.is(i)){if(o.parent('div[style]').length>0){var p=o.parent('div[style]');if(p.attr('style').match('padding-top:max')){var d=o.parent('div').attr('style');o.data('ndpCookie_changeConsent',function(e,t){if(t){e.parent('div[style]').attr('style',d)}
else{e.parent('div[style]').css('padding-top',0);e.parent('div[style]').css('height','auto')}})}};o.before(n)}
else{i.prepend(n)}});this.scan(o)},detach:function(t,o,a){e('.coverplate',t).remove()},consentChange:function(){window.setTimeout(this.scan,0)},scan:o(function(t){var s=CookieControl.config(),r=s.optionalCookies,c=r.length,n={};for(var i=0;i<c;i++){var o=r[i].name.toLowerCase(),a=CookieControl.getCategoryConsent(i);n[o]=!!a;e('iframe[data-cookiecategory~="'+o+'"], embed[data-cookiecategory~="'+o+'"], script[data-cookiecategory~="'+o+'"]',t).each(function(){var t=e(this),n=e('#'+t.attr('aria-describedby')),o,i;if(a){o='data-src';i='src';if(t.is('script')){t.remove();t.removeAttr('type');t.appendTo(document.head)}}
else{o='src';i='data-src'};t.attr(i,t.attr(o)).removeAttr(o);a?n.hide():n.show();if(typeof t.data('ndpCookie_changeConsent')==='function'){t.data('ndpCookie_changeConsent')(t,a)}})};if(!e.isEmptyObject(n)&&window.dataLayer){window.dataLayer.push({'event':'cookieConsentChange','cookieConsent':n})}},300),}})(jQuery);;
